### ISSUE TITLE
Simulcast targets cannot be specified when creating a new live stream

### ISSUE THREAD

**Issue by carlosramireziii** [muxinc/mux-ruby#21]
Per the [API docs](https://docs.mux.com/reference#create-a-live-stream), the `POST /live-streams` endpoint should accept a `simulcast_targets` parameter containing an array of `SimulcastTarget` objects. The `MuxRuby::CreateLiveStreamRequest` object does not seem to implement this behavior.

**Comment by dylanjha** [comment]
Thank you @carlosramireziii. We will take a look at this and get back to you!

**Comment by GeneticGenesis** [comment]
Hey @carlosramireziii, this is fixed in 1.6.0 which I just released.

Thanks!
