### ISSUE TITLE
Gem methods returning empty ({}) responses when creating/retrieving assets

### ISSUE THREAD

**Issue by JulienDefrance** [muxinc/mux-ruby#43]
Ruby Version: 2.7.4
Rails Version: 5.2.6

These assets are successfully being created and accessible within our MUX Dashboard, 
The credentials are correct,
And the implementation follows some of the examples provided in this repository.

Skipping the SDK and Making direct HTTP calls using RestClient returns a valid response, with data Hash.

Current situation:
- Gem methods returning empty ({}) responses when creating/retrieving assets

Expected result:
- These methods should be returning valid create_asset_responses.

**Comment by eropple** [comment]
Hey there - so when this came in via Intercom I tested on our end of things, by using `examples/video/exercise_assets.rb`, and I cannot repro. Can you provide more information?

- What version of Ruby?
- What version of the SDK?
- If you invoke `examples/video/exercise_assets.rb` literally, what happens?

Thanks!

**Comment by philcluff** [comment]
Hey @JulienDefrance, please reopen this if you're able to run @eropple's tests above. 

Thanks!
