### ISSUE TITLE
Can't get response of VideoViewsAPI 

### ISSUE THREAD

**Issue by surajitcovalense** [muxinc/mux-ruby#44]
I am trying to fetch the video view list and event track by following 
openapi = MuxRuby.configure do |config|
  config.username = ENV['MUX_TOKEN_ID']
  config.password = ENV['MUX_TOKEN_SECRET']
end

# API Client Initialization
api_instance = MuxRuby::VideoViewsApi.new
result = api_instance.get_video_view(id)

incidents_api = MuxRuby::IncidentsApi.new
incidents = incidents_api.list_incidents

Its returning 

`ETHON: performed EASY effective_url=https://api.mux.com/data/v1/incidents response_code=404 return_code=ok total_time=1.112898
MuxRuby::NotFoundError: 
HTTP status code: 404
Response headers: {"cache-control"=>"max-age=0, private, must-revalidate", "content-type"=>"application/json; charset=utf-8", "date"=>"Wed, 20 Oct 2021 10:54:08 GMT", "server"=>"Mux API Server v1.135.0", "x-request-id"=>"Fq-3xWmMCuVyTiwATTQK", "content-length"=>"121"}
Response body: {"error":{"type":"not_found","messages":["The requested resource either doesn't exist or you don't have access to it."]}}` 

Can anyone help me?

**Comment by eropple** [comment]
Sorry, I mean that is it set up to grant read access to Data? You can find that when you create your token, e.g.:

![image](https://user-images.githubusercontent.com/109262/138157971-a774212b-055c-41f2-833a-093d2c734383.png)

Also - is your Mux plan one that enables incidents? You can check with our support team via the button by emailing help@mux.com.
