### ISSUE TITLE
Space API endpoints include extra $ in paths when variable substitution occurs

### ISSUE THREAD

**Issue by murraysum** [muxinc/mux-ruby#47]
**Issue**

In several of the Space API endpoints when variable substitution occurs for the SPACE_ID or BROADCAST_ID there is a `$` prepended to the identifier which makes the path incorrect. As a result the API rejects the request. For example, the create a space broadcast endpoint instead of making a request to `https://api.mux.com/video/v1/spaces/my_space_id/broadcasts` it makes a request to `https://api.mux.com/video/v1/spaces/$my_space_id/broadcasts`:

The following endpoints are effected: 

* Create a space broadcast
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L117
* Delete a space
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L182
* Delete a space broadcast
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L249
* Get a space
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L310
* Get a space broadcast
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L379
* Start a space broadcast
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L511
* Stop a space broadcast
https://github.com/muxinc/mux-ruby/blob/10dd62c01aec412769bba2c976fd7049fae42513/lib/mux_ruby/api/spaces_api.rb#L580

**How to reproduce**

The default spaces example for creating a broadcast should show you the error:
```
api_instance = MuxRuby::SpacesApi.new
space_id = 'space_id_example' # String | The space ID.
create_broadcast_request = MuxRuby::CreateBroadcastRequest.new({live_stream_id: 'live_stream_id_example'}) # CreateBroadcastRequest | 

begin
  # Create a space broadcast
  result = api_instance.create_space_broadcast(space_id, create_broadcast_request)
  p result
rescue MuxRuby::ApiError => e
  puts "Error when calling SpacesApi->create_space_broadcast: #{e}"
end
```

You should get API response something like this (redacted the space_id):

```
ETHON: performed EASY effective_url=https://api.mux.com/video/v1/spaces/$redacted_space_id/broadcasts response_code=400 return_code=ok total_time=0.563622
Error when calling SpacesApi->create_space_broadcast:
HTTP status code: 400
Response headers: {"cache-control"=>"max-age=0, private, must-revalidate", "content-type"=>"application/json; charset=utf-8", "date"=>"Mon, 13 Jun 2022 16:04:47 GMT", "server"=>"Mux API Server v1.157.23", "x-request-id"=>"Fvg5rxBASuUuMp8DfAMF", "content-length"=>"88"}
Response body: {"error":{"type":"invalid_parameters","messages":["Invalid space id, failed to parse"]}}
```

**Expected behaviour**

When variable substitution occurs in the API paths `$` is not prepended to identifiers and API requests are not rejected.

**Actual behaviour**

When variable substitution occurs in the API paths `$` is prepended to identifiers and API requests are rejected.

**Comment by eropple** [comment]
Well, this is wild. Thanks for reporting it, and in such a detailed manner. We'll look into it ASAP.

**Comment by eropple** [comment]
Fix located. Will be deploying today.

**Comment by eropple** [comment]
And fix is out with mux-ruby 3.5.2. Thanks for bringing this to our attention!

**Comment by clearlyTHUYDOAN** [comment]
@murraysum thanks for the great bug report! 🎉 

As part of our OSS contribution program, we'd love to send you some swag as our way of saying thank you and recognizing your work. Please email me at [tdoan@mux.com](mailto:tdoan@mux.com) with your details and we'll get something sent out to you! 🎁

**Comment by murraysum** [comment]
@eropple No problem at all. Thanks for fixing this so quickly, much appreciated. Loving the Mux real time API so far, it is awesome. 👏 

@clearlyTHUYDOAN Thank you very much, that is very kind of you. I'll email you my details. 👍
