### ISSUE TITLE
Please make use of releases

### ISSUE THREAD

**Issue by fidalgo** [muxinc/mux-ruby#6]
Having a git URL for fetching the code in our Gemfiles instead of releases would create problems when the code changes and we need to check the commits to check what changed and evaluate the source of the problems.

Also, deployments will take longer.

**Comment by GeneticGenesis** [comment]
Hey @fidalgo, 

Thanks for the feedback! We're still finalising our release processes and automation for our SDKs, so we'll make sure to take this into account going forward.

Thanks!

**Comment by GeneticGenesis** [comment]
Hi @fidalgo 

We've updated our release process to include tagging releases. You should now be able to depend on:

```
gem 'mux_ruby', git: 'git://github.com/muxinc/mux-ruby.git', tag: '1.1.0'
```

Thanks!
