### ISSUE TITLE
VideoView object doesn't have asset_id

### ISSUE THREAD

**Issue by maxmetcalf12** [muxinc/mux-ruby#63]
The API for get video view returns asset_id but the Ruby object doesn't have it as an attribute. Can we add asset_id to https://github.com/muxinc/mux-ruby/blob/5388e5fa867636e2056d71752ec9d8fa9aef94e1/lib/mux_ruby/models/video_view.rb so we can access it on the response? 

Thanks!

**Comment by philcluff** [comment]
Hey @maxmetcalf12, confirm that this is fixed, can you try 3.11.0 please?

Thanks!
