### ISSUE TITLE
Missing support for `max_resolution_tier` attribute

### ISSUE THREAD

**Issue by tfe** [muxinc/mux-ruby#68]
Hello, I was looking at implementing the new `max_resolution_tier` param as described here: https://www.mux.com/blog/more-pixels-fewer-problems-introducing-4k-support-for-mux-video#creating-4k-assets

However MuxRuby::CreateAssetRequest does not have this as an attribute, so trying to use this results in an exception:

`max_resolution_tier is not a valid attribute in MuxRuby::CreateAssetRequest. Please check the name to make sure it's valid. List of attributes: [:input, :playback_policy, :per_title_encode, :passthrough, :mp4_support, :normalize_audio, :master_access, :test]`

**Comment by philcluff** [comment]
Hi @tfe, thanks for letting us know.

We're working on a release for the Ruby SDK which will address this issue and add support for `max_resolution_tier`, I'll have an update soon.

Thanks.

**Comment by philcluff** [comment]
Hey @tfe, this is now available in 3.11.0.

Thanks!
