### ISSUE TITLE
Publish gem on RubyGems

### ISSUE THREAD

**Issue by fidalgo** [muxinc/mux-ruby#8]
The version published on rubygems is old: https://rubygems.org/gems/mux_ruby

 Can you please publish it?

**Comment by GeneticGenesis** [comment]
Hey @fidalgo thanks for letting us know - something clearly hasn't worked right with our release process, I'll look into this today.

Thanks!

**Comment by GeneticGenesis** [comment]
Hey @fidalgo, this is fixed now, and 1.3.0 is published to ruby gems.

Let me know if you run into any issues.

Thanks!
